#:schema ./schema.json

id = "wordpress"
name = "WordPress"
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/wordpress.png"
description = "Create a place for your business, your interests, or anything else—with the open source platform that powers the web."
docs = "https://zeabur.com/docs/marketplace/wordpress"

[source]
image = "wordpress:6-php8.2"

# memory limit 10M
command = [ "/bin/bash" ]
args = [
  "-c",
  "echo -ne 'file_uploads = On\nmemory_limit = 10M\nupload_max_filesize = 10M\npost_max_size = 10M\nmax_execution_time = 120' > /usr/local/etc/php/conf.d/upload.ini && docker-entrypoint.sh apache2-foreground"
]

[[ports]]
id = "web"
port = 80
type = "HTTP"

[[volumes]]
id = "data"
dir = "/var/www/html/wp-content"

[[configs]]
path = "/var/www/html/wp-config.php"
template = """<?php

if (!function_exists('getenv_docker')) {
	function getenv_docker($env, $default) {
		if ($fileEnv = getenv($env . '_FILE')) {
			return rtrim(file_get_contents($fileEnv), "\r\n");
		}
		else if (($val = getenv($env)) !== false) {
			return $val;
		}
		else {
			return $default;
		}
	}
}

define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', 'wordpress') );
define( 'DB_USER', getenv_docker('WORDPRESS_DB_USER', 'example username') );
define( 'DB_PASSWORD', getenv_docker('WORDPRESS_DB_PASSWORD', 'example password') );

define( 'DB_HOST', getenv_docker('WORDPRESS_DB_HOST', 'mysql') );
define( 'DB_CHARSET', getenv_docker('WORDPRESS_DB_CHARSET', 'utf8') );
define( 'DB_COLLATE', getenv_docker('WORDPRESS_DB_COLLATE', '') );

define( 'AUTH_KEY',         getenv_docker('WORDPRESS_AUTH_KEY',         'b5703d7e2fff54eb27af2d5d71718418a4285d93') );
define( 'SECURE_AUTH_KEY',  getenv_docker('WORDPRESS_SECURE_AUTH_KEY',  '266068c6a79054edb1549ef4e8d7ac9161d8ae22') );
define( 'LOGGED_IN_KEY',    getenv_docker('WORDPRESS_LOGGED_IN_KEY',    '8d48501345a93e588fb364374d9c4e3d37ab42c6') );
define( 'NONCE_KEY',        getenv_docker('WORDPRESS_NONCE_KEY',        'fa4dae194949d8530fdd337384a6dc91f1154b84') );
define( 'AUTH_SALT',        getenv_docker('WORDPRESS_AUTH_SALT',        '10b42a9840a7fb7ff3d8a57275cef17451f85038') );
define( 'SECURE_AUTH_SALT', getenv_docker('WORDPRESS_SECURE_AUTH_SALT', '45c7e22c7c005a39f32f9a338ae03af86f14c967') );
define( 'LOGGED_IN_SALT',   getenv_docker('WORDPRESS_LOGGED_IN_SALT',   'ceda7f55fc77c0d7b8429a34f918ba7636594eb4') );
define( 'NONCE_SALT',       getenv_docker('WORDPRESS_NONCE_SALT',       'e64aa6eb6b68c950b32f2e89e76581dbf6e6edd7') );

$table_prefix = getenv_docker('WORDPRESS_TABLE_PREFIX', 'wp_');

define( 'WP_DEBUG', !!getenv_docker('WORDPRESS_DEBUG', '') );

if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
	$_SERVER['HTTPS'] = 'on';
}

define('FS_METHOD', 'direct');

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
"""

[env]
WORDPRESS_DB_USER = { default = "${MYSQL_USERNAME}" }
WORDPRESS_DB_PASSWORD = { default = "${MYSQL_PASSWORD}" }
WORDPRESS_DB_NAME = { default = "${MYSQL_DATABASE}" }
WORDPRESS_DEBUG = { default = "0" }
WORDPRESS_DB_HOST = { default = "${MYSQL_HOST}:${MYSQL_PORT}" }
